

- name: Remove default config file
  file:
    path: /etc/vault.d/vault.hcl
    state: absent

- name: Add vault config
  copy:
    src: ./files/vault.hcl
    dest: /etc/vault.d/vault.hcl
    mode: 0664
    group: vault
    owner: vault

- name: Add vault service file
  copy:
    src: ./files/vault.service
    dest: /lib/systemd/system/vault.service
    mode: 0664
    group: root
    owner: root


- name: Set cap_ipc_lock=+ep
  capabilities:
    path: /usr/bin/vault
    capability: cap_ipc_lock=+ep
    state: present

- name: Enable vault
  service:
    name: vault
    state: stopped
    enabled: true

- name: Add letsencrypt deploy hook
  copy:
    src: ./files/letsencrypt-deploy-hook.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/vault-restart.sh
    mode: 0664
    group: root
    owner: root

