

- name: Remove default config file
  file:
    path: /etc/vault.d/vault.hcl
    state: absent

- name: Touch config file
  file:
    path: /etc/vault.d/vault.hcl
    state: touch
    group: vault
    owner: vault
    mode: 0660

- name: Add vault config template
  copy:
    src: ./files/vault.hcl
    dest: /etc/vault.d/vault.hcl
    mode: 0664
    group: vault
    owner: vault

- name: Add config injection script
  copy:
    src: ./files/inject-conf.sh
    dest: /etc/vault.d/inject-conf.sh
    mode: 0774
    group: vault
    owner: vault

- name: Add vault service file
  copy:
    src: ./files/vault.service
    dest: /lib/systemd/system/vault.service
    mode: 0664
    group: root
    owner: root

- name: Add vault config injector service
  copy:
    src: ./files/vault-config-injector.service
    dest: /lib/systemd/system/vault-config-injector.service
    mode: 0664
    group: root
    owner: root

- name: Set cap_ipc_lock=+ep
  capabilities:
    path: /usr/bin/vault
    capability: cap_ipc_lock=+ep
    state: present

- name: Enable vault
  service:
    name: vault
    state: stopped
    enabled: true

- name: Enable vault config injector
  service:
    name: vault-config-injector
    state: stopped
    enabled: true


