- name: Ensure config dir is present and has the right mode
  file:
    path: /etc/vault.d/
    state: directory
    mode: 0775
    owner: vault
    group: vault

- name: Ensure storage dir is present and has the right mode
  file:
    path: /opt/vault-data
    state: directory
    mode: 0770
    owner: vault
    group: vault

- name: Remove default config file
  file:
    path: /etc/vault.d/vault.hcl
    state: absent

- name: Remove default config file
  file:
    path: /etc/vault.d/vault.hcl
    state: absent

- name: Add vault config
  copy:
    src: ./files/00-vault.hcl.tpl
    dest: /etc/vault.d/00-vault.hcl.tpl
    mode: 0664
    group: vault
    owner: vault

- name: Add vault entrypoint script
  copy:
    src: ./files/vault-entrypoint.sh
    dest: /usr/bin/vault-entrypoint.sh
    mode: 0774
    group: vault
    owner: vault

- name: Add vault service file
  copy:
    src: ./files/vault.service
    dest: /lib/systemd/system/vault.service
    mode: 0664
    group: root
    owner: root

- name: Set cap_ipc_lock=+ep
  capabilities:
    path: /usr/bin/vault
    capability: cap_ipc_lock=+ep
    state: present

- name: Enable vault
  service:
    name: vault
    state: stopped
    enabled: true

- name: Add letsencrypt deploy hook
  copy:
    src: ./files/letsencrypt-deploy-hook.sh
    dest: /etc/letsencrypt/renewal-hooks/deploy/vault-restart.sh
    mode: 0664
    group: root
    owner: root

