---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    vars: 
      consul_server: true
      consul_template_entrypoint_vault_role: consul-server
    roles:
      - consul
      - consul-template