---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    vars:
      consul_server: true
      vault_role: consul-server
    roles:
      - vault_agent
      - consul
      - consul_template
