---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Make sure default user is here
  user:
    name: dotkom
    append: true
    groups:
      - wheel
    state: present
    createhome: yes
    shell: /bin/bash

- name: Install vault autocompletion
  shell: vault -autocomplete-install && complete -C /usr/bin/vault vault
  ignore_errors: yes
  args:
    executable: /bin/bash
    