- name: Install packages
  apt:
    pkg:
      - consul={{ consul_version }}
      - dnsmasq
    state: present

- name: Remove default config
  file:
    path: /etc/consul.d/consul.hcl
    state: absent

- name: Touch config file
  file:
    path: /etc/consul.d/consul.hcl
    state: touch
    group: consul
    owner: consul
    mode: 0660

- name: Touch CA file
  file:
    path: /etc/consul.d/ca.crt
    state: touch
    group: consul
    owner: consul
    mode: 0664

- name: Touch cert file
  file:
    path: /etc/consul.d/agent.crt
    state: touch
    group: consul
    owner: consul
    mode: 0664

  when: consul_server | bool

- name: Touch cert key file
  file:
    path: /etc/consul.d/agent.key
    state: touch
    group: consul
    owner: consul
    mode: 0660

  when: consul_server | bool

- name: Touch config file
  file:
    path: /etc/consul.d/consul.hcl
    state: touch
    group: consul
    owner: consul
    mode: 0770

- name: Add key rotation script
  copy:
    src: ./files/rotate-gossip-key.sh
    dest: /etc/consul.d/rotate-gossip-key.sh
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add key Template
  copy:
    src: ./files/consul-template/server/gossip.key.tpl
    dest: /etc/consul.d/gossip.key.tpl
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add consul template config
  copy:
    src: ./files/consul-template/{{ consul_server | ternary('server', 'client') }}/consul-templates.hcl
    dest: /etc/consul_template.d/consul-templates.hcl
    mode: 0664
    group: root
    owner: root

- name: Add ca template
  copy:
    src: ./files/consul-template/ca.crt.tpl
    dest: /etc/consul.d/ca.crt.tpl
    mode: 0664
    group: consul
    owner: consul

- name: Add agent cert template
  copy:
    src: ./files/consul-template/server/agent.crt.tpl
    dest: /etc/consul.d/agent.crt.tpl
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add agent key template
  copy:
    src: ./files/consul-template/server/agent.key.tpl
    dest: /etc/consul.d/agent.key.tpl
    mode: 0664
    group: consul
    owner: consul

- name: Add consul config template
  copy:
    src: ./files/00-consul-{{ consul_server | ternary('server', 'client') }}.hcl
    dest: /etc/consul.d/00-consul.hcl
    mode: 0660
    group: consul
    owner: consul

- name: Add consul service file
  copy:
    src: ./files/consul.service
    dest: /lib/systemd/system/consul.service
    mode: 0664
    group: root
    owner: root

- name: Enable consul
  service:
    name: consul
    state: stopped
    enabled: true

- name: Recreate /etc/resolv.conf
  copy:
    src: ./files/resolv.conf
    dest: /etc/resolv.conf
    mode: 0664
    group: root
    owner: root

- name: Delete symlinked /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Recreate /etc/resolv.conf
  copy:
    src: ./files/resolv.conf
    dest: /etc/resolv.conf
    mode: 0664
    group: root
    owner: root

- name: Add dnsmasq config
  template:
    src: ./templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/dnsmasq.conf
    mode: 0664
    group: root
    owner: root

- name: Update dhcp config
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: "supersede domain-name-servers 127.0.0.1, 169.254.169.253;"

- name: Disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Enable dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true

