- name: Install packages
  apt:
    pkg:
      - consul={{ consul_version }}
      - dnsmasq
    state: present

- name: Remove default config
  file:
    path: /etc/consul.d/consul.hcl
    state: absent

- name: Touch config file
  file:
    path: /etc/consul.d/consul.hcl
    state: touch
    group: consul
    owner: consul
    mode: 0660

- name: Touch CA file
  file:
    path: /etc/consul.d/ca.crt
    state: touch
    group: consul
    owner: consul
    mode: 0664

- name: Touch cert file
  file:
    path: /etc/consul.d/agent.crt
    state: touch
    group: consul
    owner: consul
    mode: 0664

  when: consul_server | bool

- name: Touch cert key file
  file:
    path: /etc/consul.d/agent.key
    state: touch
    group: consul
    owner: consul
    mode: 0660

  when: consul_server | bool

- name: Touch config file
  file:
    path: /etc/consul.d/consul.hcl
    state: touch
    group: consul
    owner: consul
    mode: 0770

- name: Add config injection script
  template:
    src: ./templates/inject-conf.sh.j2
    dest: /etc/consul.d/inject-conf.sh
    mode: 0774
    group: consul
    owner: consul

- name: Add key rotation script
  copy:
    src: ./files/rotate-gossip-key.sh
    dest: /etc/consul.d/rotate-gossip-key.sh
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add key Template
  copy:
    src: ./files/gossip.key.tpl
    dest: /etc/consul.d/gossip.key
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add consul service file
  copy:
    src: ./files/consul.service
    dest: /lib/systemd/system/consul.service
    mode: 0664
    group: root
    owner: root

- name: Add consul template config
  template:
    src: ./templates/templates.hcl.j2
    dest: /etc/consul_template.d/consul_templates.hcl
    mode: 0664
    group: root
    owner: root

- name: Add ca template
  template:
    src: ./templates/ca.crt.tpl.j2
    dest: /etc/consul.d/ca.crt.tpl
    mode: 0664
    group: consul
    owner: consul

- name: Add agent cert template
  template:
    src: ./templates/agent.crt.tpl.j2
    dest: /etc/consul.d/agent.crt.tpl
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add agent key template
  template:
    src: ./templates/agent.key.tpl.j2
    dest: /etc/consul.d/agent.key.tpl
    mode: 0664
    group: consul
    owner: consul

- name: Add consul config template
  template:
    src: ./templates/consul.hcl.tpl.j2
    dest: /etc/consul.d/consul.hcl.tpl
    mode: 0660
    group: consul
    owner: consul

- name: Add consul template config
  template:
    src: ./templates/templates.hcl.j2
    dest: /etc/consul_template.d/consul_templates.hcl
    mode: 0664
    group: root
    owner: root

- name: Add consul config injector service
  template:
    src: ./templates/consul-config-injector.service.j2
    dest: /lib/systemd/system/consul-config-injector.service
    mode: 0664
    group: root
    owner: root

- name: Enable consul
  service:
    name: consul
    state: stopped
    enabled: true

- name: Enable consul config injector
  service:
    name: consul-config-injector
    state: stopped
    enabled: true

- name: Recreate /etc/resolv.conf
  copy:
    src: ./files/resolv.conf
    dest: /etc/resolv.conf
    mode: 0664
    group: root
    owner: root

- name: Delete symlinked /etc/resolv.conf
  file:
    path: /etc/resolv.conf
    state: absent

- name: Recreate /etc/resolv.conf
  copy:
    src: ./files/resolv.conf
    dest: /etc/resolv.conf
    mode: 0664
    group: root
    owner: root

- name: Add dnsmasq config
  template:
    src: ./templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/dnsmasq.conf
    mode: 0664
    group: root
    owner: root

- name: Update dhcp config
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: "supersede domain-name-servers 127.0.0.1, 169.254.169.253;"

- name: Disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Enable dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true

