- name: Download Promtail
  get_url:
    url: https://github.com/grafana/loki/releases/download/{{ promtail_version }}/promtail-linux-amd64.zip
    dest: /tmp/promtail.zip

- name: Unzip Promtail
  unarchive:
    remote_src: true
    src: /tmp/promtail.zip
    dest: /tmp/

- name: Copy executable to right location
  copy:
    src: /tmp/promtail-linux-amd64
    dest: /usr/bin/promtail
    mode: 0775
    remote_src: true

- name: Ensure config dir exists
  file:
    path: /etc/promtail.d/
    state: directory
    mode: 0775

- name: Ensure consul template dir exists
  file:
    path: /etc/promtail.d/consul-template
    state: directory
    mode: 0775

- name: Ensure data dir exists
  file:
    path: /opt/promtail/
    state: directory
    mode: 0775


- name: Add config temlate
  copy:
    src: ./files/consul-template/conf.yml.tpl
    dest: /etc/promtail.d/consul-template/conf.yml.tpl
    mode: 0664

- name: Add consul template config
  copy:
    src: ./files/consul-template/exec.hcl
    dest: /etc/promtail.d/consul-template/exec.hcl
    mode: 0664

- name: Add Service file
  copy:
    src: ./files/promtail.service
    dest: /usr/lib/systemd/system/promtail.service
    mode: 0664

- name: Enable promtail
  service:
    name: promtail
    state: stopped
    enabled: true