---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    roles:
      - base
      - vault_agent
      - consul_template
      - consul
      - prometheus_node_exporter
