---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    roles:
      - base
      - vault-agent
      - consul-template
      - consul
      - prometheus_node_exporter
