---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    vars:
      vault_role: nomad-server
      nomad_server: true
    roles:
      - vault-agent
      - consul-template
      - consul
      - nomad

