---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    vars:
      consul_template_vault_role: nomad-server
      nomad_server: true
    roles:
      - consul_template
      - consul
      - nomad

