- name: Overwrite ca template
  copy:
    src: ./files/ca.crt.tpl
    dest: /etc/nomad.d/ca.crt.tpl
    mode: 0664
    group: nomad
    owner: nomad

- name: Overwrite agent cert template
  copy:
    src: ./files/agent.crt.tpl
    dest: /etc/nomad.d/agent.crt.tpl
    mode: 0664
    group: nomad
    owner: nomad

- name: Overwrite agent key template
  copy:
    src: ./files/agent.key.tpl
    dest: /etc/nomad.d/agent.key.tpl
    mode: 0664
    group: nomad
    owner: nomad

- name: Overwrite nomad config
  template:
    src: ./templates/nomad.hcl.tpl.j2
    dest: /etc/nomad.d/nomad.hcl.tpl
    mode: 0660
    group: nomad
    owner: nomad
