---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    vars:
      vault_role: vault-server
      letsencrypt_certs: ["vault.online.ntnu.no"]
    roles:
      - vault-agent
      - consul
      - consul-template
      - letsencrypt
      - vault_server