---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    vars:
      consul_template_vault_role: vault-server
      letsencrypt_certs: ["vault.online.ntnu.no"]
    roles:
      - consul
      - consul_template
      - letsencrypt
      - vault_server