---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    vars: 
      is_vault_server: true
      consul_node_name_prefix: vault-server
    roles:
      - consul
      - vault-server