- name: Install packages
  apt:
    pkg: 
      - nomad={{ nomad_version }}
      - dnsmasq
    state: present

- name: Install consul autocompletion
  shell: consul -autocomplete-install && complete -C /usr/bin/consul consul
  ignore_errors: yes
  args:
    executable: /bin/bash

- name: Touch CA file
  file: 
    path: /etc/consul.d/ca.crt
    state: touch
    group: consul
    owner: consul

- name: Touch cert file
  file: 
    path: /etc/consul.d/agent.crt
    state: touch
    group: consul
    owner: consul
  when: consul_server | bool

- name: Touch cert key file
  file: 
    path: /etc/consul.d/agent.key
    state: touch
    group: consul
    owner: consul
  when: consul_server | bool

- name: Touch config file
  file: 
    path: /etc/consul.d/consul.hcl
    state: touch
    group: consul
    owner: consul
    mode: 0770

- name: Add config injection script
  copy: 
    src: ./files/inject-conf.{{(consul_server | ternary('server', 'client'))}}.sh
    dest: /etc/consul.d/inject-conf.sh
    mode: 0664
    group: consul
    owner: consul

- name: Add key rotation script
  copy: 
    src: ./files/rotate-gossip-key.sh
    dest: /etc/consul.d/rorate-gossip-key.sh
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add key Template
  copy: 
    src: ./files/gossip-key.key.tpl
    dest: /etc/consul.d/gossip-key.key
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add consul template config
  template: 
    src: ./templates/templates.hcl.j2
    dest: /etc/consul_template.d/consul_templates.hcl
    mode: 0664
    group: root
    owner: root

- name: Add ca template
  template: 
    src: ./templates/ca.crt.tpl.j2
    dest: /etc/consul.d/ca.crt.tpl
    mode: 0664
    group: consul
    owner: consul

- name: Add agent cert template
  template: 
    src: ./templates/agent.crt.tpl.j2
    dest: /etc/consul.d/agent.crt.tpl
    mode: 0664
    group: consul
    owner: consul
  when: consul_server | bool

- name: Add agent key template
  template: 
    src: ./templates/agent.key.tpl.j2
    dest: /etc/consul.d/agent.key.tpl
    mode: 0664
    group: consul
    owner: consul

- name: Add consul config template
  template: 
    src: ./templates/consul.{{ ( consul_server | ternary('server', 'client') ) }}.tpl.j2
    dest: /etc/consul.d/consul.hcl.tpl
    mode: 0660
    group: consul
    owner: consul

- name: Add consul template config
  template: 
    src: ./templates/templates.hcl.j2
    dest: /etc/consul_template.d/consul_templates.hcl
    mode: 0664
    group: root
    owner: root

- name: Recreate /etc/resolv.conf
  copy: 
    src: ./files/resolv.conf
    dest: /etc/resolv.conf
    mode: 0664
    group: root
    owner: root

- name: Delete symlinked /etc/resolv.conf
  file: 
    path: /etc/resolv.conf
    state: absent

- name: Recreate /etc/resolv.conf
  copy: 
    src: ./files/resolv.conf
    dest: /etc/resolv.conf
    mode: 0664
    group: root
    owner: root

- name: Add dnsmasq config
  template: 
    src: ./templates/dnsmasq.conf.j2
    dest: /etc/dnsmasq.d/dnsmasq.conf
    mode: 0664
    group: root
    owner: root

- name: Update dhcp config
  lineinfile:
    dest: /etc/dhcp/dhclient.conf
    line: "supersede domain-name-servers 127.0.0.1, 169.254.169.253;"
    
- name: Disable systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: false
    
- name: Enable dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true

