- name: Install packages
  apt:
    name: nomad={{ nomad_version }}
    state: present

- name: Remove default config
  file:
    path: /etc/nomad.d/nomad.hcl
    state: absent

- name: Touch config file
  file:
    path: /etc/nomad.d/nomad.hcl
    state: touch
    group: nomad
    owner: nomad
    mode: 0660

- name: Touch CA file
  file:
    path: /etc/nomad.d/ca.crt
    state: touch
    group: nomad
    owner: nomad
    mode: 0664

- name: Touch cert file
  file:
    path: /etc/nomad.d/agent.crt
    state: touch
    group: nomad
    owner: nomad
    mode: 0664

- name: Touch cert key file
  file:
    path: /etc/nomad.d/agent.key
    state: touch
    group: nomad
    owner: nomad
    mode: 0660

- name: Add nomad service file
  copy:
    src: ./files/nomad.service
    dest: /lib/systemd/system/nomad.service
    mode: 0664
    group: root
    owner: root

- name: Add config injection script
  template:
    src: ./templates/inject-conf.sh.j2
    dest: /etc/nomad.d/inject-conf.sh
    mode: 0774
    group: nomad
    owner: nomad

- name: Add ca template
  copy:
    src: ./files/ca.crt.tpl
    dest: /etc/nomad.d/ca.crt.tpl
    mode: 0664
    group: nomad
    owner: nomad

- name: Add agent cert template
  copy:
    src: ./files/agent.crt.tpl
    dest: /etc/nomad.d/agent.crt.tpl
    mode: 0664
    group: nomad
    owner: nomad

- name: Add agent key template
  copy:
    src: ./files/agent.key.tpl
    dest: /etc/nomad.d/agent.key.tpl
    mode: 0664
    group: nomad
    owner: nomad

- name: Add nomad config
  template:
    src: ./templates/nomad.hcl.tpl.j2
    dest: /etc/nomad.d/nomad.hcl.tpl
    mode: 0660
    group: nomad
    owner: nomad

- name: Add consul template config
  copy:
    src: ./files/templates.hcl
    dest: /etc/consul_template.d/nomad_templates.hcl
    mode: 0664
    group: root
    owner: root

- name: Add nomad config injector service
  copy:
    src: ./files/nomad-config-injector.service
    dest: /lib/systemd/system/nomad-config-injector.service
    mode: 0664
    group: root
    owner: root

- name: Add nomad user to docker group
  user:
    name: nomad
    groups:
      - docker
      - nomad
  when: not nomad_server | bool

- name: Make CNI plugin folder
  file:
    path: /opt/cni/bin
    state: directory
    mode: 0664
  when: not nomad_server | bool

- name: Downlaod CNI plugin
  get_url:
    url: https://github.com/containernetworking/plugins/releases/download/v0.9.0/cni-plugins-linux-amd64-v0.9.0.tgz
    dest: /tmp/cni.tar.gz
  when: not nomad_server | bool

- name: Unzip CNI plugin
  unarchive:
    src: /tmp/cni.tar.gz
    dest: /opt/cni/bin
    remote_src: true
  when: not nomad_server | bool

- name: Configure iptables
  sysctl:
    name: net.bridge.bridge-nf-call-arptables
    value: "1"
    state: present
  when: not nomad_server | bool

- name: Configure iptables
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: "1"
    state: present
  when: not nomad_server | bool

- name: Configure iptables
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: "1"
    state: present
  when: not nomad_server | bool

- name: Enable nomad config injector
  service:
    name: nomad-config-injector
    state: stopped
    enabled: true

- name: Enable nomad
  service:
    name: nomad
    state: stopped
    enabled: true