- name: Add Docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Update apt and install docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Add daemon config
  copy:
    src: ./files/daemon.json
    dest: /etc/docker/daemon.json
    mode: 0644
    group: root
    owner: root

- name: Enable docker
  service:
    name: docker
    state: started
    enabled: true
