---
  - name: Delete symlinked /etc/resolv.conf
    file: 
      path: /etc/resolv.conf
      state: absent

  - name: Recreate /etc/resolv.conf
    copy: 
      src: ./files/resolv.conf
      dest: /etc/resolv.conf
      mode: 0640
      group: root
      owner: root

  - name: Add dnsmasq config
    copy: 
      src: ./files/dnsmasq.conf
      dest: /etc/dnsmasq.d/dnsmasq.conf
      mode: 0640
      group: root
      owner: root

  - name: Disable systemd-resolved
    service:
      name: systemd-resolved
      state: stopped
      enabled: false
      
  - name: Enable dnsmasq
    service:
      name: dnsmasq
      state: started
      enabled: true