---
  - name: Download vault client signer public key
    get_url:
      url: "{{ vault_url }}/v1/{{vault_ssh_client_signer_path}}/public_key"
      dest: /etc/ssh/trusted-user-ca-keys.pem

  - name: Configure sshd
    lineinfile:
      path: "/etc/ssh/sshd_config"
      regex: "^(#)?{{item.key}}"
      line: "{{item.key}} {{item.value}}"
      state: present
    loop:
      - { key: "PermitRootLogin", value: "no" }
      - { key: "PasswordAuthentication", value: "no" } 
      - { key: "HostKey", value: "/etc/ssh/ssh_host_rsa_key" }
      - { key: "HostCertificate", value: "/etc/ssh/ssh_host_rsa_key-cert.pub" }
      - { key: "TrustedUserCAKeys", value: "/etc/ssh/trusted-user-ca-keys.pem" }
       
  - name: Restart sshd
    service:
      name: sshd
      enabled: true
      state: restarted