---
  - name: Setup image
    hosts: localhost
    connection: local
    become: yes
    vars:
      vault_role: nomad-client
    roles:
      - vault_agent
      - consul
      - consul_template
      - docker
      - nomad

