name: "Packer"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: "Check"
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    steps:
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: https://vault.online.ntnu.no:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              aws/creds/vault-gh-actions-packer-baseline access_key;
              aws/creds/vault-gh-actions-packer-baseline secret_key
              
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer.pkr.hcl
      - name: test
        run: aws sts get-caller-identity
        env:
          AWS_ACCESS_KEY_ID: ${{ steps.secrets.outputs.access_key }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.secrets.outputs.secret_key }}
      - name: Build AWS AMI
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: -except=vagrant.testing
        env:
          PACKER_LOG: 1

      - name: Remove test ami
        run: |
          aws ec2 deregister-image --image-id \
          $(aws ec2 describe-images --filter "Name=tag:environment,Values=testing" --query 'Images[0].[ImageId]' --output text)

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: https://vault.online.ntnu.no:8200
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              aws/creds/vault-gh-actions-packer-baseline access_key | AWS_ACCESS_KEY_ID ;
              aws/creds/vault-gh-actions-packer-baseline secret_key | AWS_SECRET_ACCESS_KEY ;

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build AWS AMI
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: -except=vagrant.testing -var environement=prod
        env:
          PACKER_LOG: 1

      
