name: "Validate"

on:
  pull_request:
    branches:
      - main
env:
  VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
  VAULT_ADDR: https://vault.online.ntnu.no:8200
jobs:
  validate-packer:
    name: Validate packer templates
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["base", "consul-server", "nomad-client", "nomad-server", vault-server]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: images/${{ matrix.image }}
  lint:
    name: Lint Ansible Roles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            ./ansible/roles/base
            ./ansible/roles/consul
            ./ansible/roles/consul-template
            ./ansible/roles/docker
            ./ansible/roles/nomad
            ./ansible/roles/nomad_server
            ./ansible/roles/prometheus_node_exporter
            ./ansible/roles/vault_server